plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.2.2.cjs

packageExtensions:
  "react-hot-loader@*":
    dependencies:
      "@hot-loader/react-dom": "*"
  "react-pixi-fiber@*":
    dependencies:
      "prop-types": "*"
  "react-redux@*":
    dependencies:
      "@hot-loader/react-dom": "*"
      "redux": "*"
  "redux-devtools-extension@*":
    dependencies:
      "redux": "*"
